version: "3.8"
services:
  # nomi frontend
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "0.0.0.0:3000:3000"
    restart: unless-stopped
